services:

  elements-esplora:
    build: ./esplora
    environment:
      - "DEBUG=VERBOSE"
      - "NO_REGTEST_MINING=1"
    volumes:
      - elements-esplora-data:/data
    command:
      - liquid-regtest
      - explorer
    ports:
      - "8092:80"
    network_mode: "host"
        
        
volumes:
  elements-esplora-data:
    
